---
- hosts: aws
  become: true
  tasks:
#    - name: Add new repository
#      apt_repository:
#        repo: deb http://security.ubuntu.com/ubuntu hirsute-security main

    - name: Add MongoDB GPG key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-6.0.asc
        state: present

    - name: Add MongoDB repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse
        state: present

    - name: Add new repository
      apt_repository:
        repo: deb http://security.ubuntu.com/ubuntu hirsute-security main

    - name: Install libssl1.1 package
      apt:
        name: libssl1.1
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
        allow_unauthenticated: yes

