- name: Installation og MongoDB
  hosts: aws
  become: true
  vars:
    os_variety: jammy
    mongo_version: 6.0
  tasks:
    - apt: update_cache=yes

    - name: Install required packages
      apt:
        pkg: 
          - gnupg2
          - software-properties-common
          - apt-transport-https
          - lsb-release
          - ca-certificates

    - name: Import public key
      apt_key:
        url: 'https://www.mongodb.org/static/pgp/server-{{ mongo_version }}.asc'
        state: present      

    - apt: update_cache=yes

    # - name: Adding MongoDB public GPG key
    #   shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
    #   when: ansible_facts['lsb']['release'] == "22.04"

    - apt: update_cache=yes

    - name: Creating a repo file
      file:
         path: /etc/apt/sources.list.d/mongodb-org-6.0.list
         state: touch   

    - name: Add MongoDB repository
      lineinfile: >
         line="deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{os_variety}}/mongodb-org/6.0 multiverse"
         dest=/etc/apt/sources.list.d/mongodb-org-6.0.list
         state=present

    - apt: update_cache=yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
        allow_unauthenticated: yes
      notify: 
        - start mongodb

  handlers:
    - name: start mongodb
      service: name=mongod state=started

