---
- name: Install MongoDB 6.0
  hosts: aws
  become: true
  vars:
    mongodb_version: "6.0"
  tasks:
  - name: Add MongoDB repository key
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
      state: present
  - name: Add MongoDB repository to sources list
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/{{ mongodb_version }} multiverse
      state: present
  - name: Install MongoDB
    apt:
      name: mongodb-org
      state: present
      update_cache: yes
