---
- name: Installing NodeJS with NVM
  remote_user: bow-dev
  hosts: bow
  become: true
  vars:
     version: 18
  tasks:

    - name: Configuring NVM in a System
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
   
    - name: Setting required Environment to use NVM & Installing node
      shell: source ~/.bashrc && source ~/.profile  
      args:
         executable: /bin/bash

    - name: Installing Node
      shell: source ~/.nvm/nvm.sh && source ~/.bashrc && nvm install {{ version }}
      args:
        executable: /bin/bash
