---
- name: Installing PHP Version {{ php_version }}
  hosts: icecat
  become: true
  vars:
    php_version: 8.1
  tasks:

  #  - apt: update_cache=yes
  #  - name: Installing Apache2
  #    apt:
  #      name: apache2
  #      state: latest

   - name: Installing Software Common Properties
     apt: 
       name: software-properties-common

   - name: Adding Ondrej PPA
     apt_repository: 
       repo: ppa:ondrej/php
       update_cache: yes 
   - name: Installing PHP Version {{ php_version }}
     apt:
       name: "php{{ php_version }}"
       state: present

   - name: Installing require PHP Packages
     apt:
       pkg:
         - libapache2-mod-php{{ php_version }}
         - php{{ php_version }}-common
         - php{{ php_version }}-curl
         - php{{ php_version }}-mbstring
         - php{{ php_version }}-xmlrpc
         - php{{ php_version }}-mysql
         - php{{ php_version }}-mysqlnd
         - php{{ php_version }}-opcache
         - php{{ php_version }}-dev
         - php{{ php_version }}-gd
         - php{{ php_version }}-xml
         - php{{ php_version }}-intl
         - php{{ php_version }}-ldap
         - php{{ php_version }}-imagick
         - php{{ php_version }}-cli
         - php{{ php_version }}-zip
         - php{{ php_version }}-bcmath 
         - php{{ php_version }}-fpm
         - php{{ php_version }}-soap
         - php{{ php_version }}-json
         - php{{ php_version }}-gmp
         - php{{ php_version }}-dom
         - php{{ php_version }}-mcrypt
         - php{{ php_version }}-iconv
         - php{{ php_version }}-xsl
         - php{{ php_version }}-ctype
         - php{{ php_version }}-pdo
         - php{{ php_version }}-bz2
         - php{{ php_version }}-calendar
         - php{{ php_version }}-fileinfo
         - php{{ php_version }}-tokenizer
         - php{{ php_version }}-xmlwriter
         - php{{ php_version }}-xmlreader
         - php{{ php_version }}-phar
       state: present

  #  - name: Enabling Apache Module for FASTCGI
  #    apache2_module:
  #       name: "{{ item }}"
  #       state: present
  #    with_items:
  #         - actions
  #         - alias
  #         - proxy_fcgi
  #         - rewrite
  #    notify: Check Status of Apache2

  # handlers:
  #  - name: Check Status of Apache2
  #    service: 
  #       name: apache2
  #       state: restarted  
